name: Orchestrate Releases

on:
  workflow_dispatch:
    inputs:
      deploy_repo1:
        type: boolean
        default: false
        description: "Trigger release workflow in repo1"
      deploy_repo2:
        type: boolean
        default: false
        description: "Trigger release workflow in repo2"
      deploy_repo3:
        type: boolean
        default: false
        description: "Trigger release workflow in repo3"
      branch:
        description: "Branch to deploy"
        type: choice
        options:
          - main
          - branch2

jobs:
  orchestrate:
    runs-on: ubuntu-latest

    steps:

      - name: generate version
        id: version
        run: |
          VERSION=$(date +'%Y-%m-%d-%H%M%S')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Trigger repo1 release
        if: ${{ inputs.deploy_repo1 }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_BVIS }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/anicolaebujitsu/repo1/dispatches \
            -d '{"event_type": "trigger-release"}'

      - name: Trigger repo2 release
        if: ${{ inputs.deploy_repo2 }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_BVIS }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/anicolaebujitsu/repo2/dispatches \
            -d '{"event_type": "trigger-release", "client_payload": {"branch": "${{ inputs.branch }}", "version": "${{ steps.version.outputs.version }}"}}'

      - name: Trigger repo3 release
        if: ${{ inputs.deploy_repo3 }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_BVIS }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/anicolaebujitsu/repo3/dispatches \
            -d '{"event_type": "trigger-release", "client_payload": {"branch": "${{ inputs.branch }}", "version": "${{ steps.version.outputs.version }}"}}'
